### ISSUE TITLE
ejercicio 

### ISSUE THREAD

**Issue by Gonzalo-Garcia-C** [fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-Gonzalo-Garcia-C#1]
subo el archivo del promedio con signo para corregir

https://github.com/fiuba-labo-de-micro-miercoles/2019-2c-primer-proyecto-Gonzalo-Garcia-C/blob/master/codigo/promedio.asm

**Comment by rarias** [comment]
Antes de main: te faltaría un .org INT_VECTORS_SIZE
Líneas 29 y 30 mal, no es correcta la inicialización de Z
Líneas 34-37 no hacen lo que se espera (si r18<0, r22=0xFF, sino r22=0x00)
Faltan algunas líneas en el main:
   rcall promedio
x_siempre: rjmp x_siempre
pór ejemplo.
